In [17]:
import numpy as np
from discreteMSE.entropy import apen, sampen, vector_matches
#from discreteMSE.entropy import apen, sampen

In [44]:
#data = np.array([6, 1, 6, 8, 7, 2, 2, 7, 5, 2, 5, 5, 4, 5, 5, 6, 6, 1, 1, 1])
data = np.array([1, 1, 1, 3, 1, 2, 2, 3, 1, 2])
m=2
N=len(data)

In [37]:
xmi = np.array([data[i:i+m] for i in range(len(data)-m+1)])
z = len(xmi)
print(xmi)
print('---------')
#create 3d array of xmi vectors where each xi in xmi is its own 1xm subarray
xi_matrix = np.stack([xmi], axis=2).reshape((z,1,m))

#dif is a 3D array containing the pairwise kronecker delta between xi and xmi for all xi.
dif = np.invert(xi_matrix==xmi).astype(int)
print(dif)
#dif.sum(axis=2) evaluates to 0 for xi that fully matched and >0 for xi that did not fully match
sim_dist = dif.sum(axis=2)
print(sim_dist)

[[1 1]
 [1 1]
 [1 3]
 [3 1]
 [1 2]
 [2 2]
 [2 3]
 [3 1]
 [1 2]]
---------
[[[0 0]
  [0 0]
  [0 1]
  [1 0]
  [0 1]
  [1 1]
  [1 1]
  [1 0]
  [0 1]]

 [[0 0]
  [0 0]
  [0 1]
  [1 0]
  [0 1]
  [1 1]
  [1 1]
  [1 0]
  [0 1]]

 [[0 1]
  [0 1]
  [0 0]
  [1 1]
  [0 1]
  [1 1]
  [1 0]
  [1 1]
  [0 1]]

 [[1 0]
  [1 0]
  [1 1]
  [0 0]
  [1 1]
  [1 1]
  [1 1]
  [0 0]
  [1 1]]

 [[0 1]
  [0 1]
  [0 1]
  [1 1]
  [0 0]
  [1 0]
  [1 1]
  [1 1]
  [0 0]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 0]
  [0 0]
  [0 1]
  [1 1]
  [1 0]]

 [[1 1]
  [1 1]
  [1 0]
  [1 1]
  [1 1]
  [0 1]
  [0 0]
  [1 1]
  [1 1]]

 [[1 0]
  [1 0]
  [1 1]
  [0 0]
  [1 1]
  [1 1]
  [1 1]
  [0 0]
  [1 1]]

 [[0 1]
  [0 1]
  [0 1]
  [1 1]
  [0 0]
  [1 0]
  [1 1]
  [1 1]
  [0 0]]]
[[0 0 1 1 1 2 2 1 1]
 [0 0 1 1 1 2 2 1 1]
 [1 1 0 2 1 2 1 2 1]
 [1 1 2 0 2 2 2 0 2]
 [1 1 1 2 0 1 2 2 0]
 [2 2 2 2 1 0 1 2 1]
 [2 2 1 2 2 1 0 2 2]
 [1 1 2 0 2 2 2 0 2]
 [1 1 1 2 0 1 2 2 0]]


In [54]:
np.sum(sim_dist[:-1,:]==0) - z

4

In [38]:
N = len(data)
Bi = vector_matches(data[:-1], m, enttype='apen')
k=m+1
Ai = vector_matches(data, k, enttype='apen')
print('N-m', N-m)
print('Bi', len(Bi), 'Ai', len(Ai))
print(Bi.shape == Ai.shape)
apen = np.sum(np.negative(np.log(Ai/Bi)))/(N-m)

N-m 8
Bi 8 Ai 8
True


In [40]:
Bi

array([2, 2, 1, 2, 1, 1, 1, 2])

In [39]:
Ai

array([1, 1, 1, 2, 1, 1, 1, 2])

In [41]:
Ai/Bi

array([0.5, 0.5, 1. , 1. , 1. , 1. , 1. , 1. ])

In [42]:
np.log(Ai/Bi)

array([-0.69314718, -0.69314718,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

In [43]:
np.sum(np.negative(np.log(Ai/Bi)))

1.3862943611198906

In [45]:
np.sum(np.negative(np.log(Ai/Bi)))/(N-m)

0.17328679513998632

In [46]:
apen

0.17328679513998632

In [51]:
B = vector_matches(data[:-1], m, enttype='sampen')
#print(B)

#get number of matches, store in variable 'A'
k = m+1
A = vector_matches(data, k, enttype='sampen')

In [52]:
B

4

In [53]:
A

2